name: Test workflow

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: checkout code 
      uses: actions/checkout@v4

    - name: Test variable prededence 
      run: echo ${{ vars.TEST }}

    # - name: upgrade pip
    #   run: pip install --upgrade pip

    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    # - name: Install dependencies
    #   run: |
    #       pip install -r requirements.txt
