name: CI

on:
  push


jobs:

  job1:
    runs-on: ubuntu-latest
    name: job1
    steps: 
        - name: 
          run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    name: job2
    steps: 
      - name: exit 
        run: exit 1 
  job3:
    runs-on: ubuntu-latest
    name: job3
    needs: [job1, job2]
    steps: 
      - name: 
        run: echo "job3" 
  job4: 
    runs-on: ubuntu-latest

    name: job4
    steps: 
      - name: 
        run: | 
          echo "job4"
          wait 10
