name: CI

on:
  push


jobs:
  job1:
    name: job1
  job2:
    needs: job1
    name: job2
    steps: 
        run: | 
        exit 1
  job3:
    name: job3
    needs: [job1, job2]

  job4: 
    name: job4
